In [ ]:

import pandas as pd

## Load data (kick_1) from a CSV file ##

kick = pd.read_csv('kick_1.csv') # There are mixed data types in columns

C:\Users\ndoyl\AppData\Local\Temp\ipykernel_3628\982005266.py:5: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  kick = pd.read_csv('kick_1.csv') # There are mixed data types in columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41476 entries, 0 to 41475
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   PurchaseID                         41476 non-null  int64
 1   PurchaseTimestamp                  41476 non-null  int64
 2   PurchaseDate                       41476 non-null  object
 3   Auction                            41432 non-null  object
 4   VehYear                            41432 non-null  float64
 5   Make                               41432 non-null  object
 6   Color                              41432 non-null  object
 7   Transmission                       41432 non-null  object
 8   WheelTypeID                        41432 non-null  object
 9   WheelType                          41380 non-null  object
 10  VehOdo                             41432 non-null  float64
 11  Nationality                        41432 non-null  object
 12  Size                               41432 non-null  object
 13  TopThreeAmericanName               41432 non-null  object
 14  MMRAcquisitionAuctionAveragePrice  41416 non-null  object
 15  MMRAcquisitionAuctionCleanPrice    41429 non-null  object
 16  MMRAcquisitionRetailAveragePrice   41429 non-null  object
 17  MMRAcquisitonRetailCleanPrice      41327 non-null  object
 18  MMRCurrentAuctionAveragePrice      41429 non-null  object
 19  MMRCurrentAuctionCleanPrice        41429 non-null  object
 20  MMRCurrentRetailAveragePrice       41409 non-null  object
 21  MMRCurrentRetailCleanPrice         41409 non-null  object
 22  MMRCurrentRetailRatio              41116 non-null  object
 23  PRIMEUNIT                          41432 non-null  object
 24  AUCGUART                           41432 non-null  object
 25  VNST                               41432 non-null  object
 26  VehBCost                           41432 non-null  object
 27  IsOnlineSale                       41432 non-null  object
 28  WarrantyCost                       41432 non-null  float64
 29  ForSale                            41476 non-null  object
 30  IsBadBuy                           41476 non-null  int64
dtypes: float64(3), int64(3), object(25)
memory usage: 9.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41476 entries, 0 to 41475
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   PurchaseID                         41476 non-null  int64
 1   PurchaseTimestamp                  41476 non-null  int64
 2   PurchaseDate                       41476 non-null  object
 3   Auction                            41432 non-null  object
 4   VehYear                            41432 non-null  float64
 5   Make                               41432 non-null  object
 6   Color                              41432 non-null  object
 7   Transmission                       41432 non-null  object
 8   WheelTypeID                        41432 non-null  object
 9   WheelType                          41380 non-null  object
 10  VehOdo                             41432 non-null  float64
 11  Nationality                        41432 non-null  object
 12  Size                               41432 non-null  object
 13  TopThreeAmericanName               41432 non-null  object
 14  MMRAcquisitionAuctionAveragePrice  41416 non-null  object
 15  MMRAcquisitionAuctionCleanPrice    41429 non-null  object
 16  MMRAcquisitionRetailAveragePrice   41429 non-null  object
 17  MMRAcquisitonRetailCleanPrice      41327 non-null  object
 18  MMRCurrentAuctionAveragePrice      41429 non-null  object
 19  MMRCurrentAuctionCleanPrice        41429 non-null  object
 20  MMRCurrentRetailAveragePrice       41409 non-null  object
 21  MMRCurrentRetailCleanPrice         41409 non-null  object
 22  MMRCurrentRetailRatio              41116 non-null  object
 23  PRIMEUNIT                          41432 non-null  object
 24  AUCGUART                           41432 non-null  object
 25  VNST                               41432 non-null  object
 26  VehBCost                           41432 non-null  object
 27  IsOnlineSale                       41432 non-null  object
 28  WarrantyCost                       41432 non-null  float64
 29  ForSale                            41476 non-null  object
 30  IsBadBuy                           41476 non-null  int64
dtypes: float64(3), int64(3), object(25)
memory usage: 9.8+ MB

                                   Missing Values  Percentage Missing
MMRCurrentRetailRatio                         360                0.87
MMRAcquisitonRetailCleanPrice                 149                0.36
WheelType                                      96                0.23
MMRCurrentRetailCleanPrice                     67                0.16
MMRCurrentRetailAveragePrice                   67                0.16
MMRAcquisitionAuctionAveragePrice              60                0.14
MMRAcquisitionAuctionCleanPrice                47                0.11
MMRCurrentAuctionAveragePrice                  47                0.11
MMRAcquisitionRetailAveragePrice               47                0.11
MMRCurrentAuctionCleanPrice                    47                0.11
Size                                           44                0.11
Nationality                                    44                0.11
VehOdo                                         44                0.11
WheelTypeID                                    44                0.11
Color                                          44                0.11
Transmission                                   44                0.11
Make                                           44                0.11
VehYear                                        44                0.11
Auction                                        44                0.11
TopThreeAmericanName                           44                0.11
PRIMEUNIT                                      44                0.11
AUCGUART                                       44                0.11
VNST                                           44                0.11
VehBCost                                       44                0.11
IsOnlineSale                                   44                0.11
WarrantyCost                                   44                0.11

np.int64(0)

IsBadBuy
0    36105
1     5371
Name: count, dtype: int64
IsBadBuy
0    87.050342
1    12.949658
Name: proportion, dtype: float64

                             Variable  Unique Values
0                          PurchaseID          41476
1                              VehOdo          28604
2               MMRCurrentRetailRatio          25870
3       MMRAcquisitonRetailCleanPrice          11583
4          MMRCurrentRetailCleanPrice          11363
5    MMRAcquisitionRetailAveragePrice          11070
6        MMRCurrentRetailAveragePrice          10935
7     MMRAcquisitionAuctionCleanPrice          10010
8         MMRCurrentAuctionCleanPrice           9890
9   MMRAcquisitionAuctionAveragePrice           9271
10      MMRCurrentAuctionAveragePrice           9183
11                           VehBCost           1869
12                  PurchaseTimestamp            497
13                       PurchaseDate            497
14                       WarrantyCost            271
15                               VNST             31
16                               Make             30
17                              Color             17
18                               Size             13
19                            VehYear             10
20                       IsOnlineSale              8
21                            ForSale              6
22                        Nationality              6
23                        WheelTypeID              5
24               TopThreeAmericanName              5
25                          WheelType              4
26                       Transmission              4
27                            Auction              3
28                           AUCGUART              3
29                          PRIMEUNIT              3
30                           IsBadBuy              2

In [ ]:

# Show all columns information #
kick.info()

# View headings of kick_1 #
pd.set_option('display.max_columns', None) # Display all columns. # 
kick.head()

In [ ]:

kick.shape # Rows, columns #
kick.columns # Names of columns. # 
kick.info() # Data types #
kick.describe() # Overview of numerical columns. #

# Missing values, percentages and rank in kick_1 # 

missing = (                                  # What values are missing. #
    kick.isnull()
        .sum()
        .to_frame(name='Missing Values')
)

missing['Percentage Missing'] = (   # What percentage values are missing. #
    missing['Missing Values'] / len(kick) * 100
).round(2)

missing = missing[                  # Only show volumns with missing variables. #
    missing['Missing Values'] > 0
]

missing = (                                 # Ascensding oreder of values missing. #
    missing.sort_values(
        'Missing Values',
        ascending=False

    )
)
display(missing) # Displqy missinf values, percentages and rank in kink_1. #

In [ ]:

# Check for duplicate records in kick_1 #

duplicates  = kick.duplicated().sum() 
display(duplicates)

# Check for records that are missing the same values. #

kick[kick.isnull().sum(axis=1) > 10]

In [ ]:

# Check class distribution & percentage

print(kick['IsBadBuy'].value_counts())
print(kick['IsBadBuy'].value_counts(normalize=True) * 100)

In [ ]:

# Summary statistics of numerical columns in kick_1 #

kick.describe().round(2) # Round to 2 decimal places. # 

# The number of unique values in each column in kick_1 #

cardinality = (
    kick.nunique()
        .sort_values(ascending=False) # In descending order #
        .reset_index()
)

cardinality.columns = ['Variable', 'Unique Values']
display(cardinality) # Display the number of unique values in each column. #